### ISSUE TITLE
⚡ is a wide symbol

### ISSUE THREAD

**Issue by BerserkerTroll** [chubin/wttr.in#100]
![11](https://cloud.githubusercontent.com/assets/20418480/25150651/550e640e-248b-11e7-872d-2efa457937d7.png)

**Comment by chubin** [comment]
Is it in a console or in a browser? I mean the screenshot
Could you please check it in the console also?

**Comment by BerserkerTroll** [comment]
In a terminal emulator.
From http://www.unicode.org/Public/9.0.0/ucd/EastAsianWidth.txt:
`26A1;W           # So         HIGH VOLTAGE SIGN`
If I am not mistaken, `W` means [East Asian Wide](http://unicode.org/reports/tr11/#ED4). I believe that it basically means that the character occupies two columns in a terminal.

**Comment by chubin** [comment]
Yes, you are right, that is a bug and it should be fixed. Thank you for the reporting!

**Comment by chubin** [comment]
What location is that?

**Comment by BerserkerTroll** [comment]
http://wttr.in/Ташкент

**Comment by chubin** [comment]
Strange enough but it works in the browser

**Comment by BerserkerTroll** [comment]
Maybe because the browser is built with old Unicode data and defaults to width 1.
I don't know from where does terminal emulator get information that 26A1 has witdh of 2, because `wcwidth(0x26A1) ` returns `-1`, i.e. current version of glibc doesn't know about this character (should be fixed in 2.26). I think it uses font's data about glyphs width. (BTW `wcwidth == -1` leads to edition glitches in bash (readline?) if there is ⚡ in the current line).
`utf8proc_charwidth(0x26a1)` (function from utf8proc library) correctly return `2`.

**Comment by chubin** [comment]
@DirtYiCE @BerserkerTroll @MAGICCC @cig0 @slump64
The problem is fixed. Please test.
Does it work for you?

Place where the everlasting thunder:

curl wttr.in/:test-thunder
https://wttr.in/:test-thunder (in browser)
http://de.wttr.in/:test-thunder.png

**Comment by slump64** [comment]
browser:
![image](https://user-images.githubusercontent.com/14310552/41186142-2a76329c-6b9a-11e8-8d83-758be9e14171.png)
terminal:
![image](https://user-images.githubusercontent.com/14310552/41186145-3d6e7346-6b9a-11e8-9ecf-2cd52c24f0dd.png)

**Comment by chubin** [comment]
@slump64 So it is still broken in Chrome, but it works fine in firefox as far as I can see. I'm curios what about other browsers

**Comment by cig0** [comment]
Hey @chubin,
- Working well in iTerm2 and Terminal.app
- Broken on all browsers I tried, each on it latests version: Safari (macOS + iOS), Chrome, Brave (macOS + iOS), TorBrowser, Firefox

**Comment by Pimon1** [comment]
I justed tested it, it's neither working in iTerm2 or Terminal.app nor in the browser (Firefox 61). And besides, the voltage signs/emojis are not shown in the terminal screenshot from @slump64 (or are they currently blinking?).

This is `wttr.in/:thunder-test` in iTerm2:

![wttr in](https://user-images.githubusercontent.com/40452746/43889408-5c5d25cc-9bc4-11e8-9253-2e4220e3fdb8.png)

**Comment by cig0** [comment]
This is weird, it's working well on my iTerm2:

![screen shot 2018-08-09 at 21 04 42](https://user-images.githubusercontent.com/394089/43932070-7536e340-9c18-11e8-95a6-525054476ee2.png)

![screen shot 2018-08-09 at 21 07 13](https://user-images.githubusercontent.com/394089/43932073-77ca5aa6-9c18-11e8-83df-7d2e32bacc94.png)

**Comment by slump64** [comment]
you should do your next project in Golang if you want to work with unicode for sure

**Comment by Nikorasu** [comment]
I'm still seeing this broken, in both my terminals and browsers with various fonts.. It appears the same.
![weatherglitch](https://user-images.githubusercontent.com/1338231/44700283-f423f100-aa4d-11e8-9804-e456a26a7329.PNG)

**Comment by BerserkerTroll** [comment]
@chubin ok in mate-terminal (version 1.20), but Firefox thinks that it is a narrow character.
